name: dependent-type-search
version: 0.1.0.0
github: "githubuser/dependent-type-search"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

data-files:
  - migration/*.sql
  - static/*.css

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/dependent-type-search#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - Agda
  - bytestring
  - containers
  - deepseq
  - directory
  - filepath
  - filemanip
  - flat
  - foldl
  - hashable
  - haskeline
  - hasql
  - hasql-dynamic-statements
  - hasql-migration
  - hasql-pool
  - hasql-th
  - hasql-transaction
  - lucid
  - megaparsec
  - mtl
  - named
  - nonempty-containers
  - opt-env-conf
  - parser-combinators
  - prettyprinter
  - prettyprinter-ansi-terminal
  - profunctors
  - repline
  - servant
  - servant-lucid
  - servant-server
  - streamly
  - text
  - time
  - unordered-containers
  - vector
  - wai
  - warp
  - witherable

language: GHC2021

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - CPP
  - DataKinds
  - DerivingVia
  - DeriveAnyClass
  - DuplicateRecordFields
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - InstanceSigs
  - ImplicitParams
  - KindSignatures
  - LambdaCase
  - MultilineStrings
  - MultiParamTypeClasses
  - MultiWayIf
  - NoFieldSelectors
  - NoImplicitPrelude
  - OrPatterns
  - OverloadedLabels
  - OverloadedStrings
  - OverloadedRecordDot
  - PackageImports
  - PatternSynonyms
  - PolyKinds
  - QualifiedDo
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - Strict
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - UndecidableInstances
  - UnboxedTuples
  - UnboxedSums
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing
  - -O2
  - -funbox-strict-fields
  - -threaded

flags:
  debug:
    description: turn on debug traces
    default: false
    manual: true
  dump:
    description: dump core
    default: false
    manual: true
  llvm:
    description: use llvm for codegen
    default: false
    manual: true

when:
  - condition: flag(debug)
    cpp-options:
      - -DDEBUG
  - condition: flag(dump)
    ghc-options:
      - -ddump-simpl
      - -dsuppress-all
      - -dno-suppress-type-signatures
      - -ddump-to-file
  - condition: flag(llvm)
    ghc-options:
      - -fllvm

library:
  source-dirs: src

executables:
  dependent-type-search:
    main: Main.hs
    source-dirs: app
    dependencies:
      - dependent-type-search
    when:
      - condition: flag(debug)
        then:
          ghc-options:
            - -threaded
        else:
          ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts= "-A64M -N4"

tests:
  dependent-type-search-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - dependent-type-search
